apiVersion: v1
kind: Service
metadata:
  name: {{ include "mastrao-recording-egress.fullname" . }}
  labels:
    {{- include "mastrao-recording-egress.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.metrics.serviceAnnotations | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mastrao-recording-egress.selectorLabels" . | nindent 4 }}
  ports:
    - name: health
      port: {{ .Values.health.port }}
      targetPort: health
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
