apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mastrao-recording-egress.fullname" . }}
  labels:
    {{- include "mastrao-recording-egress.labels" . | nindent 4 }}
automountServiceAccountToken: false
