# Generated by Django 5.2.16 on 2026-08-18 20:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_mastrao_recording_consent"),
    ]

    operations = [
        migrations.CreateModel(
            name="MastraoActiveSpeakerSample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("participant_ref", models.CharField(max_length=200)),
                ("speaking_started_at_ms", models.PositiveBigIntegerField()),
                (
                    "speaking_ended_at_ms",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "recording_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_speaker_samples",
                        to="core.mastraorecordingbinding",
                    ),
                ),
            ],
            options={
                "db_table": "meet_mastrao_active_speaker_sample",
                "ordering": ("speaking_started_at_ms",),
            },
        ),
        migrations.CreateModel(
            name="MastraoTranscriptionBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("organization_external_id", models.CharField(max_length=200)),
                ("meeting_ref", models.CharField(max_length=160)),
                ("room_ref", models.CharField(max_length=100)),
                ("recording_ref", models.CharField(max_length=160)),
                ("transcription_ref", models.CharField(max_length=160, unique=True)),
                ("artifact_ref", models.CharField(max_length=160)),
                ("provider_binding_digest", models.CharField(max_length=64)),
                ("artifact_checksum_digest", models.CharField(max_length=64)),
                ("artifact_byte_size", models.PositiveBigIntegerField()),
                (
                    "purpose",
                    models.CharField(default="meeting_transcription", max_length=64),
                ),
                (
                    "scope",
                    models.CharField(default="recording_artifact_audio", max_length=80),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("prepared", "Prepared"),
                            ("processing", "Processing"),
                            ("available", "Available"),
                            ("failed", "Failed"),
                        ],
                        default="prepared",
                        max_length=20,
                    ),
                ),
                (
                    "transcript_artifact_ref",
                    models.CharField(
                        blank=True, max_length=160, null=True, unique=True
                    ),
                ),
                (
                    "object_ref",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("byte_size", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "checksum_algorithm",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "checksum_digest",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("segment_count", models.PositiveIntegerField(blank=True, null=True)),
                ("engine_ref", models.CharField(blank=True, max_length=160, null=True)),
                ("transcript_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recording_binding",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transcription_binding",
                        to="core.mastraorecordingbinding",
                    ),
                ),
            ],
            options={
                "db_table": "meet_mastrao_transcription_binding",
            },
        ),
        migrations.CreateModel(
            name="MastraoTranscriptionEffect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("effect_key", models.CharField(max_length=160, unique=True)),
                ("operation", models.CharField(default="transcribe", max_length=16)),
                ("arguments_digest", models.CharField(max_length=64)),
                ("effect_jti", models.CharField(max_length=200, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("applying", "Applying"),
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "provider_observation",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("receipt_claims", models.JSONField(blank=True, default=dict)),
                (
                    "receipt_digest",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transcription_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="effects",
                        to="core.mastraotranscriptionbinding",
                    ),
                ),
            ],
            options={
                "db_table": "meet_mastrao_transcription_effect",
            },
        ),
        migrations.AddConstraint(
            model_name="mastraotranscriptionbinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("provider_binding_digest__regex", "^[a-f0-9]{64}$")
                ),
                name="mastrao_transcription_provider_digest_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="mastraotranscriptionbinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("artifact_checksum_digest__regex", "^[a-f0-9]{64}$")
                ),
                name="mastrao_transcription_artifact_digest_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="mastraotranscriptionbinding",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose", "meeting_transcription")),
                name="mastrao_transcription_purpose_fixed",
            ),
        ),
        migrations.AddConstraint(
            model_name="mastraotranscriptionbinding",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope", "recording_artifact_audio")),
                name="mastrao_transcription_scope_fixed",
            ),
        ),
        migrations.AddConstraint(
            model_name="mastraotranscriptioneffect",
            constraint=models.UniqueConstraint(
                fields=("transcription_binding", "operation"),
                name="unique_mastrao_transcription_operation",
            ),
        ),
        migrations.AddConstraint(
            model_name="mastraotranscriptioneffect",
            constraint=models.CheckConstraint(
                condition=models.Q(("arguments_digest__regex", "^[a-f0-9]{64}$")),
                name="mastrao_transcription_effect_digest_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="mastraotranscriptioneffect",
            constraint=models.CheckConstraint(
                condition=models.Q(("operation", "transcribe")),
                name="mastrao_transcription_operation_fixed",
            ),
        ),
    ]
