# Generated by Django 5.2.16 on 2026-08-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_mastrao_transcription"),
    ]

    operations = [
        migrations.AddField(
            model_name="mastraotranscriptioneffect",
            name="dispatch_state",
            field=models.CharField(
                choices=[
                    ("dispatch_pending", "Dispatch pending"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    (
                        "artifact_notification_pending",
                        "Artifact notification pending",
                    ),
                    (
                        "failure_notification_pending",
                        "Failure notification pending",
                    ),
                    ("completed", "Completed"),
                ],
                default="dispatch_pending",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="mastraotranscriptioneffect",
            name="failure_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="mastraotranscriptioneffect",
            index=models.Index(
                fields=["dispatch_state", "updated_at"],
                name="mastrao_tx_dispatch_idx",
            ),
        ),
    ]
