# Generated by Django 5.2.16 on 2026-08-21 14:20

# 0029 and 0030 exist only on feat/meeting-transcription. They are not
# ancestors of origin/main, so they have never been deployed with
# persistent rows. APPLIED/FAILED effects therefore cannot inherit the
# 0030 default dispatch_pending, and no neutralizing data migration is
# required.

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_mastrao_transcription_dispatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="mastraotranscriptioneffect",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mastraotranscriptioneffect",
            name="next_attempt_at",
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddIndex(
            model_name="mastraotranscriptioneffect",
            index=models.Index(
                fields=["dispatch_state", "next_attempt_at"],
                name="mastrao_tx_dispatch_due_idx",
            ),
        ),
    ]
