# Generated by Django 5.2.16 on 2026-08-21 19:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_mastrao_transcription_dispatch_backoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="MastraoTranscriptionProviderAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("generation", models.PositiveIntegerField(default=1)),
                ("attempt_ref", models.CharField(max_length=160, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("prepared", "Prepared"),
                            ("sending", "Sending"),
                            ("result_received", "Result received"),
                            ("artifact_write_pending", "Artifact write pending"),
                            ("succeeded", "Succeeded"),
                            ("failed_pre_egress", "Failed before egress"),
                            ("unknown", "Unknown"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="prepared",
                        max_length=32,
                    ),
                ),
                ("provider_ref", models.CharField(max_length=32)),
                ("requested_model_ref", models.CharField(max_length=160)),
                ("adapter_version", models.CharField(max_length=40)),
                ("request_config_digest", models.CharField(max_length=64)),
                ("audio_sha256", models.CharField(max_length=64)),
                ("audio_duration_ms", models.PositiveIntegerField()),
                ("audio_codec", models.CharField(max_length=40)),
                ("input_bytes", models.PositiveBigIntegerField()),
                (
                    "gateway_request_ref_digest",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "provider_request_ref_digest",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "resolved_model_ref",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("usage_audio_seconds", models.FloatField(blank=True, null=True)),
                (
                    "estimated_cost_micros",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("currency", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "result_checksum",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "result_recovery_ref",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "transcript_object_ref",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "cleanup_state",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "last_safe_error_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_attempts",
                        to="core.mastraotranscriptioneffect",
                    ),
                ),
            ],
            options={
                "db_table": "meet_mastrao_transcription_provider_attempt",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("effect", "generation"),
                        name="unique_mastrao_tx_provider_attempt_generation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(audio_sha256__regex=r"^[a-f0-9]{64}$"),
                        name="mastrao_tx_attempt_audio_digest_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            request_config_digest__regex=r"^[a-f0-9]{64}$"
                        ),
                        name="mastrao_tx_attempt_config_digest_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            provider_ref__in=["fake", "mistral", "openai"]
                        ),
                        name="mastrao_tx_attempt_provider_closed",
                    ),
                ],
            },
        ),
    ]
