# Generated by Django 5.2.16 on 2026-08-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_mastrao_transcription_provider_attempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mastraotranscriptioneffect",
            name="dispatch_state",
            field=models.CharField(
                choices=[
                    ("dispatch_pending", "Dispatch pending"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    (
                        "artifact_notification_pending",
                        "Artifact notification pending",
                    ),
                    (
                        "failure_notification_pending",
                        "Failure notification pending",
                    ),
                    ("cleanup_pending", "Cleanup pending"),
                    ("completed", "Completed"),
                ],
                default="dispatch_pending",
                max_length=40,
            ),
        ),
    ]
