# Generated by Django 5.2.16 on 2026-08-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_alter_mastraotranscriptioneffect_dispatch_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mastraotranscriptionbinding",
            name="recording_binding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transcription_bindings",
                to="core.mastraorecordingbinding",
            ),
        ),
        migrations.AddField(
            model_name="mastraotranscriptionbinding",
            name="contract_operation_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="mastraotranscriptionbinding",
            name="asr_profile_ref",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="mastraotranscriptionbinding",
            name="asr_profile_digest",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="mastraotranscriptionbinding",
            name="asr_provider_ref",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="mastraotranscriptionbinding",
            name="requested_model_ref",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="mastraotranscriptionbinding",
            name="request_config_digest",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="mastraotranscriptionbinding",
            name="normalization_version",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="mastraotranscriptionbinding",
            name="processing_region_ref",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="mastraotranscriptionbinding",
            name="data_control_ref",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddConstraint(
            model_name="mastraotranscriptionbinding",
            constraint=models.CheckConstraint(
                condition=models.Q(contract_operation_version__in=[1, 2]),
                name="mastrao_tx_contract_version_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="mastraotranscriptionbinding",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        contract_operation_version=1,
                        asr_profile_ref__isnull=True,
                        asr_profile_digest__isnull=True,
                        asr_provider_ref__isnull=True,
                        requested_model_ref__isnull=True,
                        request_config_digest__isnull=True,
                        normalization_version__isnull=True,
                        processing_region_ref__isnull=True,
                        data_control_ref__isnull=True,
                    )
                    | models.Q(
                        contract_operation_version=2,
                        asr_profile_ref__isnull=False,
                        asr_profile_digest__isnull=False,
                        asr_provider_ref__isnull=False,
                        requested_model_ref__isnull=False,
                        request_config_digest__isnull=False,
                        normalization_version__isnull=False,
                        processing_region_ref__isnull=False,
                        data_control_ref__isnull=False,
                    )
                ),
                name="mastrao_tx_profile_complete_by_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="mastraotranscriptionbinding",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(asr_provider_ref__isnull=True)
                    | models.Q(asr_provider_ref__in=["fake", "mistral", "openai"])
                ),
                name="mastrao_tx_binding_provider_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="mastraotranscriptionbinding",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(asr_profile_digest__isnull=True)
                    | models.Q(asr_profile_digest__regex="^[a-f0-9]{64}$")
                ),
                name="mastrao_tx_profile_digest_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="mastraotranscriptionbinding",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(request_config_digest__isnull=True)
                    | models.Q(request_config_digest__regex="^[a-f0-9]{64}$")
                ),
                name="mastrao_tx_config_digest_format",
            ),
        ),
    ]
