# Generated by Django 5.2.16 on 2026-08-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_mastrao_transcription_managed_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mastraotranscriptionproviderattempt",
            name="state",
            field=models.CharField(
                choices=[
                    ("prepared", "Prepared"),
                    ("sending", "Sending"),
                    ("result_received", "Result received"),
                    ("artifact_write_pending", "Artifact write pending"),
                    ("succeeded", "Succeeded"),
                    ("failed_pre_egress", "Failed before egress"),
                    ("rate_limited", "Rate limited"),
                    ("unknown", "Unknown"),
                    ("cancelled", "Cancelled"),
                ],
                default="prepared",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="mastraotranscriptionproviderattempt",
            name="terminal_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("failed_pre_egress", "Failed before egress"),
                    ("rejected", "Rejected"),
                    ("unknown", "Unknown"),
                    ("deleted", "Deleted"),
                    ("conflict", "Conflict"),
                ],
                max_length=24,
                null=True,
            ),
        ),
    ]
