# Generated by Django 5.2.16 on 2026-09-10 05:34

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_mastraohostgrant_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MastraoMediaTokenBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("rtc_identity", models.CharField(max_length=255)),
                ("grant_digest", models.CharField(max_length=64)),
                ("session_nonce_digest", models.CharField(max_length=64)),
                ("authorization_digest", models.CharField(max_length=64)),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                (
                    "guest_grant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.mastraoguestgrant",
                    ),
                ),
                (
                    "host_grant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.mastraohostgrant",
                    ),
                ),
                (
                    "room_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.mastraoroombinding",
                    ),
                ),
            ],
            options={
                "db_table": "meet_mastrao_media_token_binding",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("guest_grant__isnull", True),
                                ("host_grant__isnull", False),
                            ),
                            models.Q(
                                ("guest_grant__isnull", False),
                                ("host_grant__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="mastrao_media_token_one_grant",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("issued_at"))),
                        name="mastrao_media_token_lifetime",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("grant_digest__regex", "^[a-f0-9]{64}$"),
                            ("session_nonce_digest__regex", "^[a-f0-9]{64}$"),
                            ("authorization_digest__regex", "^[a-f0-9]{64}$"),
                            ("token_digest__regex", "^[a-f0-9]{64}$"),
                        ),
                        name="mastrao_media_token_digest_formats",
                    ),
                ],
            },
        ),
    ]
