# Generated by Django 5.2.16 on 2026-09-10 06:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_mastraomediatokenbinding"),
    ]

    operations = [
        migrations.CreateModel(
            name="MastraoRtcObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("event_id", models.CharField(max_length=128, unique=True)),
                ("payload_digest", models.CharField(max_length=64)),
                ("event_type", models.CharField(max_length=32)),
                ("event_time_seconds", models.PositiveBigIntegerField()),
                ("room_sid", models.CharField(max_length=128)),
                ("participant_sid", models.CharField(max_length=128)),
                ("rtc_identity", models.CharField(max_length=255)),
                ("token_binding_ref", models.UUIDField(blank=True, null=True)),
                ("track_sid", models.CharField(blank=True, max_length=128)),
                ("track_type", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "track_source",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "room_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.mastraoroombinding",
                    ),
                ),
            ],
            options={
                "db_table": "meet_mastrao_rtc_observation",
                "indexes": [
                    models.Index(
                        fields=["room_binding", "room_sid", "participant_sid"],
                        name="mastrao_rtc_participant_idx",
                    )
                ],
            },
        ),
    ]
