# Generated by Django 5.2.16 on 2026-09-10 07:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_mastraortcobservation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MastraoRtcConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("room_sid", models.CharField(max_length=128)),
                ("participant_sid", models.CharField(max_length=128)),
                (
                    "correlation",
                    models.CharField(default="missing_join", max_length=32),
                ),
                ("ended", models.BooleanField(default=False)),
                (
                    "media_token_binding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.mastraomediatokenbinding",
                    ),
                ),
                (
                    "room_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.mastraoroombinding",
                    ),
                ),
            ],
            options={
                "db_table": "meet_mastrao_rtc_connection",
            },
        ),
        migrations.CreateModel(
            name="MastraoRtcTrackEpoch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("track_sid", models.CharField(max_length=128)),
                ("ended", models.BooleanField(default=False)),
                ("conflict", models.BooleanField(default=False)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.mastraortcconnection",
                    ),
                ),
                (
                    "first_publication",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.mastraortcobservation",
                    ),
                ),
            ],
            options={
                "db_table": "meet_mastrao_rtc_track_epoch",
            },
        ),
        migrations.AddConstraint(
            model_name="mastraortcconnection",
            constraint=models.UniqueConstraint(
                fields=("room_binding", "room_sid", "participant_sid"),
                name="mastrao_rtc_connection_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="mastraortctrackepoch",
            constraint=models.UniqueConstraint(
                fields=("connection", "track_sid"), name="mastrao_rtc_track_unique"
            ),
        ),
    ]
