# Generated by Django 5.2.16 on 2026-09-28 22:05

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_native_participant_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSubtitleControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('is_current', models.BooleanField(default=True)),
                ('room_sid', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='room_sid must be a LiveKit room SID.', regex='^RM_[A-Za-z0-9_-]{1,124}$')])),
                ('provider', models.CharField(blank=True, max_length=32, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=128, null=True)),
                ('session_id', models.CharField(blank=True, max_length=128, null=True)),
                ('control_generation', models.PositiveBigIntegerField(default=0)),
                ('state_version', models.PositiveBigIntegerField(default=0)),
                ('public_state', models.CharField(choices=[('unknown', 'Unknown'), ('inactive', 'Inactive'), ('starting', 'Starting'), ('live', 'Live'), ('reconnecting', 'Reconnecting'), ('degraded', 'Degraded'), ('unavailable', 'Unavailable'), ('stopping', 'Stopping'), ('stopped', 'Stopped')], default='inactive', max_length=16)),
                ('reason_code', models.CharField(blank=True, choices=[('dispatch_missing', 'Dispatch missing'), ('agent_missing', 'Agent missing'), ('worker_not_ready', 'Worker not ready'), ('provider_unavailable', 'Provider unavailable'), ('provider_rejected', 'Provider rejected'), ('contract_invalid', 'Contract invalid'), ('permission_denied', 'Permission denied'), ('room_finished', 'Room finished'), ('unknown', 'Unknown')], max_length=32, null=True)),
                ('observed_dispatch_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
                ('agent_present', models.BooleanField(default=False)),
                ('worker_ready', models.BooleanField(default=False)),
                ('worker_observed_at', models.DateTimeField(blank=True, null=True)),
                ('pending_since', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('desired_state', models.CharField(choices=[('OFF', 'Off'), ('ON', 'On')], default='OFF', max_length=3)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_controls', to='core.room')),
            ],
            options={
                'db_table': 'meet_room_subtitle_control',
                'indexes': [models.Index(fields=['room', 'updated_at'], name='meet_room_s_room_id_784bd9_idx')],
                'constraints': [
                    models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('room',), name='subtitle_control_one_current_room'),
                    models.CheckConstraint(condition=models.Q(('desired_state__in', ['OFF', 'ON'])), name='subtitle_control_desired_state_valid'),
                    models.CheckConstraint(condition=models.Q(('public_state__in', ['unknown', 'inactive', 'starting', 'live', 'reconnecting', 'degraded', 'unavailable', 'stopping', 'stopped'])), name='subtitle_control_public_state_valid'),
                    models.CheckConstraint(condition=models.Q(('reason_code__isnull', True), ('reason_code__in', ['dispatch_missing', 'agent_missing', 'worker_not_ready', 'provider_unavailable', 'provider_rejected', 'contract_invalid', 'permission_denied', 'room_finished', 'unknown']), _connector='OR'), name='subtitle_control_reason_code_valid'),
                    models.CheckConstraint(condition=models.Q(('observed_dispatch_ids__len__lte', 32)), name='subtitle_control_dispatch_ids_bounded'),
                ],
            },
        ),
    ]
