# Generated by Django 5.2.16 on 2026-10-03 12:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_native_source_manifest"),
    ]

    operations = [
        migrations.AddField(
            model_name="mastraohostgrant",
            name="organization_external_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="MastraoIdleCloseCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("organization_external_id", models.CharField(max_length=200)),
                ("close_request_id", models.CharField(max_length=160, unique=True)),
                ("room_sid", models.CharField(max_length=128)),
                (
                    "room_finished_event_id",
                    models.CharField(max_length=128, unique=True),
                ),
                ("room_finished_at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivering", "Delivering"),
                            ("cancelled", "Cancelled"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, default="", max_length=64)),
                (
                    "room_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idle_close_candidates",
                        to="core.mastraoroombinding",
                    ),
                ),
            ],
            options={
                "db_table": "meet_mastrao_idle_close_candidate",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("delivered_at__isnull", True), ("state", "pending")
                            ),
                            models.Q(
                                ("delivered_at__isnull", True), ("state", "delivering")
                            ),
                            models.Q(
                                ("delivered_at__isnull", True), ("state", "cancelled")
                            ),
                            models.Q(
                                ("delivered_at__isnull", False), ("state", "delivered")
                            ),
                            _connector="OR",
                        ),
                        name="mastrao_idle_close_state_shape",
                    )
                ],
            },
        ),
    ]
