# Generated by Django 5.2.16 on 2026-10-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_native_source_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastraomediatokenbinding',
            name='participant_authority',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastraortcobservation',
            name='admission_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mastraortcobservation',
            name='admission_receipt',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastraortcobservation',
            name='admission_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastraortcobservation',
            name='participant_kind',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
